apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-container
        image: trintt24/inventoryservice:latest
        ports:
        - containerPort: 80  # HTTP port
        - containerPort: 32180  # gRPC port
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: ASPNETCORE_URLS
          value: "http://+:80;http://+:32180"  # Bind to both HTTP and gRPC ports

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: NodePort
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: grpc
      port: 32180
      targetPort: 32180
      nodePort: 32180
