name: Release tag
on:
  push:
    branches:
      - main
jobs:
  tag_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN  }}
      - uses: bahmutov/npm-install@v1
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
